"""empty message

Revision ID: 767bcb01db02
Revises: 
Create Date: 2020-03-10 10:41:44.566088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '767bcb01db02'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('facebook_link', sa.String(), nullable=True))
    op.add_column('Artist', sa.Column('genres', sa.String(), nullable=True))
    op.add_column('Artist', sa.Column('image_link', sa.String(), nullable=True))
    op.add_column('Artist', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('Venue', sa.Column('facebook_link', sa.String(), nullable=True))
    op.add_column('Venue', sa.Column('image_link', sa.String(), nullable=True))
    op.add_column('Venue', sa.Column('seeking_talent', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'seeking_talent')
    op.drop_column('Venue', 'image_link')
    op.drop_column('Venue', 'facebook_link')
    op.drop_column('Artist', 'phone')
    op.drop_column('Artist', 'image_link')
    op.drop_column('Artist', 'genres')
    op.drop_column('Artist', 'facebook_link')
    # ### end Alembic commands ###
